# Generated by Django 3.0.5 on 2020-05-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='personality',
            field=models.CharField(default=str, max_length=4),
            preserve_default=False,
        ),
    ]
