# Generated by Django 3.0.5 on 2020-05-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200509_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='personality1',
            new_name='personality',
        ),
    ]
